//////////////////////////////////////////////////////////////////////////////////
// memory_map.h for Cosmos+ OpenSSD
// Copyright (c) 2017 Hanyang University ENC Lab.
// Contributed by Yong Ho Song <yhsong@enc.hanyang.ac.kr> Jaewook Kwak <jwkwak@enc.hanyang.ac.kr> Sangjin Lee
// <sjlee@enc.hanyang.ac.kr>
//
// This file is part of Cosmos+ OpenSSD.
//
// Cosmos+ OpenSSD is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation; either version 3, or (at your option)
// any later version.
//
// Cosmos+ OpenSSD is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
// See the GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Cosmos+ OpenSSD; see the file COPYING.
// If not, see <http://www.gnu.org/licenses/>.
//////////////////////////////////////////////////////////////////////////////////

//////////////////////////////////////////////////////////////////////////////////
// Company: ENC Lab. <http://enc.hanyang.ac.kr>
// Engineer: Jaewook Kwak <jwkwak@enc.hanyang.ac.kr>
//
// Project Name: Cosmos+ OpenSSD
// Design Name: Cosmos+ Firmware
// Module Name: Static Memory Allocator
// File Name: memory_map.h
//
// Version: v1.0.0
//
// Description:
//  - allocate DRAM address space (0x0010_0000 ~ 0x3FFF_FFFF) to each module
//////////////////////////////////////////////////////////////////////////////////

//////////////////////////////////////////////////////////////////////////////////
// Revision History:
//
// * v1.0.0
//   - First draft
//////////////////////////////////////////////////////////////////////////////////

#ifndef VECTOR1_COSMOS_APP_SRC_MEMORY_MAP_H_
#define VECTOR1_COSMOS_APP_SRC_MEMORY_MAP_H_

#include "address_translation.h"
#include "data_buffer.h"
#include "garbage_collection.h"
#include "gs/growingsegment.h"
#include "request_allocation.h"
#include "request_schedule.h"
#include "request_transform.h"
#include "ss/sealedsegment.h"
#include "ss/super.h"
#include "vector/hnsw.h"

#define DRAM_START_ADDR 0x00100000

#define MEMORY_SEGMENTS_START_ADDR DRAM_START_ADDR
#define MEMORY_SEGMENTS_END_ADDR 0x001FFFFF

#define NVME_MANAGEMENT_START_ADDR 0x00200000
#define NVME_MANAGEMENT_END_ADDR 0x002FFFFF

// Uncached & Unbuffered
#define RESERVED0_START_ADDR 0x00300000

#define CP_INDEX_BUFFER1_ADDR (RESERVED0_START_ADDR)
#define CP_INDEX_BUFFER1_SIZE (sizeof(struct _SEALED_SEGMENT_INDEX_NODE) * MAX_SKIPLIST_NODE * MAX_SEALED_LEVEL0 * 2)

#define CP_INDEX_BUFFER2_ADDR (CP_INDEX_BUFFER1_ADDR + CP_INDEX_BUFFER1_SIZE)
#define CP_INDEX_BUFFER2_SIZE (sizeof(struct _SEALED_SEGMENT_INDEX_NODE) * MAX_SKIPLIST_NODE * MAX_SEALED_LEVEL0 * 2)

#define CP_DATA_BUFFER1_ADDR (CP_INDEX_BUFFER2_ADDR + CP_INDEX_BUFFER2_SIZE)
#define CP_DATA_BUFFER1_SIZE (sizeof(struct _SEALED_SEGMENT_DATA_NODE) * MAX_SKIPLIST_NODE * MAX_SEALED_LEVEL0 * 2)

#define CP_DATA_BUFFER2_ADDR (CP_DATA_BUFFER1_ADDR + CP_DATA_BUFFER1_SIZE)
#define CP_DATA_BUFFER2_SIZE (sizeof(struct _SEALED_SEGMENT_DATA_NODE) * MAX_SKIPLIST_NODE * MAX_SEALED_LEVEL0 * 2)

#define COMPACTION_BUFFER_END_ADDR (CP_DATA_BUFFER2_ADDR + CP_DATA_BUFFER2_SIZE)

#define GROWING_SEGMENT_HEAD_ADDR (COMPACTION_BUFFER_END_ADDR)
#define GROWING_SEGMENT_NODE_ADDR (GROWING_SEGMENT_HEAD_ADDR + sizeof(struct _SKIPLIST_HEAD))
#define GROWING_SEGMENT_NODE_SIZE (sizeof(struct _SKIPLIST_NODE) * MAX_SKIPLIST_NODE)
#define GROWING_SEGMENT_NODE_END_ADDR (GROWING_SEGMENT_NODE_ADDR + GROWING_SEGMENT_NODE_SIZE)

#define SUPER_BLOCK_ADDR (GROWING_SEGMENT_NODE_END_ADDR)
#define SUPER_SEALED_SEGMENT_LIST_ADDR (SUPER_BLOCK_ADDR + sizeof(struct _SUPER_LEVEL_INFO))
#define SUPER_SEALED_SEGMENT_LIST0_ADDR \
  (SUPER_SEALED_SEGMENT_LIST_ADDR + (4 * sizeof(struct _SUPER_SEALED_SEGMENT_LIST)))  // The 4 indicates MAX_LEVEL.
#define SUPER_SEALED_SEGMENT_LIST1_ADDR (SUPER_SEALED_SEGMENT_LIST0_ADDR + (MAX_SEALED_LEVEL0 * sizeof(struct _SUPER_SEALED_SEGMENT_INFO)))
#define SUPER_SEALED_SEGMENT_LIST2_ADDR (SUPER_SEALED_SEGMENT_LIST1_ADDR + (MAX_SEALED_LEVEL1 * sizeof(struct _SUPER_SEALED_SEGMENT_INFO)))
#define SUPER_SEALED_SEGMENT_LIST3_ADDR (SUPER_SEALED_SEGMENT_LIST2_ADDR + (MAX_SEALED_LEVEL2 * sizeof(struct _SUPER_SEALED_SEGMENT_INFO)))
#define SUPER_SEALED_SEGMENT_LIST3_END_ADDR \
  (SUPER_SEALED_SEGMENT_LIST3_ADDR + (MAX_SEALED_LEVEL3 * sizeof(struct _SUPER_SEALED_SEGMENT_INFO)))

#define RESERVED0_END_ADDR 0x0FFFFFFF

#define FTL_MANAGEMENT_START_ADDR 0x10000000

// for data buffer
#define DATA_BUFFER_BASE_ADDR 0x10000000
#define DATA_BUFFER_SIZE (AVAILABLE_DATA_BUFFER_ENTRY_COUNT * BYTES_PER_DATA_REGION_OF_SLICE)

#define dataBufEntry2DramAddr(dataBufEntry) (DATA_BUFFER_BASE_ADDR + ((dataBufEntry)*BYTES_PER_DATA_REGION_OF_SLICE))
#define dramAddr2DataBufEntry(dramAddr) (((dramAddr)-DATA_BUFFER_BASE_ADDR) / BYTES_PER_DATA_REGION_OF_SLICE)

#define TEMPORARY_DATA_BUFFER_BASE_ADDR (DATA_BUFFER_BASE_ADDR + DATA_BUFFER_SIZE)
#define TEMPORARY_DATA_BUFFER_SIZE (AVAILABLE_TEMPORARY_DATA_BUFFER_ENTRY_COUNT * BYTES_PER_DATA_REGION_OF_SLICE)

#define SPARE_DATA_BUFFER_BASE_ADDR (TEMPORARY_DATA_BUFFER_BASE_ADDR + TEMPORARY_DATA_BUFFER_SIZE)
#define SPARE_DATA_BUFFER_SIZE (AVAILABLE_DATA_BUFFER_ENTRY_COUNT * BYTES_PER_SPARE_REGION_OF_SLICE)

#define QUERY_VECTOR_BUFFER_START_ADDR (SPARE_DATA_BUFFER_BASE_ADDR + SPARE_DATA_BUFFER_SIZE)
#define QUERY_VECTOR_BUFFER_SIZE (BYTES_PER_DATA_REGION_OF_SLICE)

// As we do not perform build job and search job in parallel, we can share memory area.
#define TOP_K_CURRENT_DISTANCE_BUFFER (QUERY_VECTOR_BUFFER_START_ADDR + QUERY_VECTOR_BUFFER_SIZE)
#define TOP_K_CURRENT_DISTANCE_BUFFER_SIZE (sizeof(VectorSearchResult))

#define TEMPORARY_SPARE_DATA_BUFFER_BASE_ADDR (TOP_K_CURRENT_DISTANCE_BUFFER + TOP_K_CURRENT_DISTANCE_BUFFER_SIZE)
#define TEMPORARY_SPARE_DATA_BUFFER_SIZE (AVAILABLE_TEMPORARY_DATA_BUFFER_ENTRY_COUNT * BYTES_PER_SPARE_REGION_OF_SLICE)

#define RESERVED_DATA_BUFFER_BASE_ADDR (TEMPORARY_SPARE_DATA_BUFFER_BASE_ADDR + TEMPORARY_SPARE_DATA_BUFFER_SIZE)
#define RESERVED_DATA_BUFFER_SIZE (COMPLETE_FLAG_TABLE_ADDR - RESERVED_DATA_BUFFER_BASE_ADDR)

// for nand request completion
#define COMPLETE_FLAG_TABLE_ADDR 0x17000000
#define COMPLETE_FLAG_TABLE_SIZE (sizeof(COMPLETE_FLAG_TABLE))

#define STATUS_REPORT_TABLE_ADDR (COMPLETE_FLAG_TABLE_ADDR + COMPLETE_FLAG_TABLE_SIZE)
#define STATUS_REPORT_TABLE_SIZE (sizeof(STATUS_REPORT_TABLE))

#define ERROR_INFO_TABLE_ADDR (STATUS_REPORT_TABLE_ADDR + STATUS_REPORT_TABLE_SIZE)
#define ERROR_INFO_TABLE_SIZE (sizeof(ERROR_INFO_TABLE))

#define TEMPORARY_PAY_LOAD_ADDR (ERROR_INFO_TABLE_ADDR + ERROR_INFO_TABLE_SIZE)
#define TEMPORARY_PAY_LOAD_SIZE BYTES_PER_DATA_REGION_OF_PAGE

#define BOUNDARY_BUFFER_ADDR (TEMPORARY_PAY_LOAD_ADDR + TEMPORARY_PAY_LOAD_SIZE)
#define BOUNDARY_BUFFER_SIZE (BYTES_PER_DATA_REGION_OF_SLICE * 8)

#define SEALED_SEGMENT_INDEX_BUFFER (BOUNDARY_BUFFER_ADDR + (BOUNDARY_BUFFER_SIZE))
#define SEALED_SEGMENT_INDEX_BUFFER_SIZE (sizeof(struct _SEALED_SEGMENT_INDEX_NODE) * (MAX_SKIPLIST_NODE * (MAX_SEALED_LEVEL0) * 2))
#define SEALED_SEGMENT_INDEX_BUFFER_END (SEALED_SEGMENT_INDEX_BUFFER + SEALED_SEGMENT_INDEX_BUFFER_SIZE)

#define SEALED_SEGMENT_DATA_BUFFER SEALED_SEGMENT_INDEX_BUFFER_END
#define SEALED_SEGMENT_DATA_BUFFER_SIZE (sizeof(struct _SEALED_SEGMENT_DATA_NODE) * MAX_SKIPLIST_NODE * MAX_SEALED_LEVEL0 * 2)
#define SEALED_SEGMENT_DATA_BUFFER_END (SEALED_SEGMENT_DATA_BUFFER + SEALED_SEGMENT_DATA_BUFFER_SIZE)

#define COMPACTION_BUFFER_ADDR (SEALED_SEGMENT_DATA_BUFFER_END)
#define COMPACTION_BUFFER_ADDR_INDEX_ONDEMAND(i) (COMPACTION_BUFFER_ADDR + ((i)*BYTES_PER_DATA_REGION_OF_SLICE))
#define COMPACTION_BUFFER_ADDR_DATA_ONDEMAND(i) \
  (COMPACTION_BUFFER_ADDR_INDEX_ONDEMAND(MAX_SEALED_LEVEL0 * 2) + ((i)*BYTES_PER_DATA_REGION_OF_SLICE))
#define COMPACTION_BUFFER_ADDR_SIZE_ONDEMAND (BYTES_PER_DATA_REGION_OF_SLICE * MAX_SEALED_LEVEL0 * 2 * 2)

#define VECTOR_INDEX_START_ADDR (COMPACTION_BUFFER_ADDR_DATA_ONDEMAND(MAX_SEALED_LEVEL0 * 2) + COMPACTION_BUFFER_ADDR_SIZE_ONDEMAND + BYTES_PER_DATA_REGION_OF_SLICE)
#define VECTOR_INDEX_SIZE (sizeof(struct _VectorIndex) * 1)

#define HNSW_ONDEMAND_ENTRY_START_ADDR (VECTOR_INDEX_START_ADDR + VECTOR_INDEX_SIZE)
#define HNSW_ONDEMAND_ENTRY_SIZE (sizeof(struct _HNSWOndemandEntry))
#define HNSW_ONDEMAND_END_ADDR HNSW_ONDEMAND_ENTRY_START_ADDR + HNSW_ONDEMAND_ENTRY_SIZE

#define DATA_BUFFER_MAP_ADDR		 		0x18000000
#define DATA_BUFFER_MAP_SIZE (sizeof(DATA_BUF_MAP))

#define DATA_BUFFFER_HASH_TABLE_ADDR (DATA_BUFFER_MAP_ADDR + DATA_BUFFER_MAP_SIZE)
#define DATA_BUFFFER_HASH_TABLE_SIZE (sizeof(DATA_BUF_HASH_TABLE))

#define TEMPORARY_DATA_BUFFER_MAP_ADDR (DATA_BUFFFER_HASH_TABLE_ADDR + DATA_BUFFFER_HASH_TABLE_SIZE)
#define TEMPORARY_DATA_BUFFER_MAP_SIZE (sizeof(TEMPORARY_DATA_BUF_MAP))

// for map tables
#define LOGICAL_SLICE_MAP_ADDR (TEMPORARY_DATA_BUFFER_MAP_ADDR + TEMPORARY_DATA_BUFFER_MAP_SIZE)
#define LOGICAL_SLICE_MAP_SIZE (sizeof(LOGICAL_SLICE_MAP))
#define VIRTUAL_SLICE_MAP_ADDR (LOGICAL_SLICE_MAP_ADDR + LOGICAL_SLICE_MAP_SIZE)
#define VIRTUAL_SLICE_MAP_SIZE (sizeof(VIRTUAL_SLICE_MAP))
#define VIRTUAL_BLOCK_MAP_ADDR (VIRTUAL_SLICE_MAP_ADDR + VIRTUAL_SLICE_MAP_SIZE)
#define VIRTUAL_BLOCK_MAP_SIZE (sizeof(VIRTUAL_BLOCK_MAP))
#define PHY_BLOCK_MAP_ADDR (VIRTUAL_BLOCK_MAP_ADDR + VIRTUAL_BLOCK_MAP_SIZE)
#define PHY_BLOCK_MAP_SIZE (sizeof(PHY_BLOCK_MAP))
#define BAD_BLOCK_TABLE_INFO_MAP_ADDR (PHY_BLOCK_MAP_ADDR + PHY_BLOCK_MAP_SIZE)
#define BAD_BLOCK_TABLE_INFO_MAP_SIZE (sizeof(BAD_BLOCK_TABLE_INFO_MAP))
#define VIRTUAL_DIE_MAP_ADDR (BAD_BLOCK_TABLE_INFO_MAP_ADDR + BAD_BLOCK_TABLE_INFO_MAP_SIZE)
#define VIRTUAL_DIE_MAP_SIZE (sizeof(VIRTUAL_DIE_MAP))

// for GC victim selection
#define GC_VICTIM_MAP_ADDR (VIRTUAL_DIE_MAP_ADDR + VIRTUAL_DIE_MAP_SIZE)
#define GC_VICTIM_MAP_SIZE (sizeof(GC_VICTIM_MAP))

// for request pool
#define REQ_POOL_ADDR (GC_VICTIM_MAP_ADDR + GC_VICTIM_MAP_SIZE)
#define REQ_POOL_SIZE (sizeof(REQ_POOL))

// for dependency table
#define ROW_ADDR_DEPENDENCY_TABLE_ADDR (REQ_POOL_ADDR + REQ_POOL_SIZE)
#define ROW_ADDR_DEPENDENCY_TABLE_SIZE (sizeof(ROW_ADDR_DEPENDENCY_TABLE))

// for request scheduler
#define DIE_STATE_TABLE_ADDR (ROW_ADDR_DEPENDENCY_TABLE_ADDR + ROW_ADDR_DEPENDENCY_TABLE_SIZE)
#define DIE_STATE_TABLE_SIZE (sizeof(DIE_STATE_TABLE))

#define RETRY_LIMIT_TABLE_ADDR (DIE_STATE_TABLE_ADDR + DIE_STATE_TABLE_SIZE)
#define RETRY_LIMIT_TABLE_SIZE (sizeof(RETRY_LIMIT_TABLE))

#define WAY_PRIORITY_TABLE_ADDR (RETRY_LIMIT_TABLE_ADDR + RETRY_LIMIT_TABLE_SIZE)
#define WAY_PRIORITY_TABLE_SIZE (sizeof(WAY_PRIORITY_TABLE))

#define FTL_MANAGEMENT_END_ADDR ((WAY_PRIORITY_TABLE_ADDR + WAY_PRIORITY_TABLE_SIZE) - 1)
#define RESERVED1_START_ADDR (FTL_MANAGEMENT_END_ADDR + 1)

#define TRASH_CAN_ADDR (RESERVED1_START_ADDR)
#define TRASH_CAN_SIZE (BYTES_PER_SPARE_REGION_OF_SLICE)

#define DIRECT_DMA_BUFFER_ADDR (TRASH_CAN_ADDR + TRASH_CAN_SIZE)
#define DIRECT_DMA_BUFFER_SIZE (BYTES_PER_SECTOR * MAX_NUM_NVME_SLOT)

#define RESERVED1_END_ADDR (DIRECT_DMA_BUFFER_ADDR + DIRECT_DMA_BUFFER_SIZE)
#define RESERVED1_SIZE (RESERVED1_END_ADDR - RESERVED1_START_ADDR)

#define DRAM_END_ADDR 0x3FFFFFFF

#endif  // VECTOR1_COSMOS_APP_SRC_MEMORY_MAP_H_
