#ifndef VECTOR1_COSMOS_APP_SRC_SS_SEALEDSEGMENT_H_
#define VECTOR1_COSMOS_APP_SRC_SS_SEALEDSEGMENT_H_

#define NUM_OF_SEALED_SEGMENT_INDEX_NODE_PER_NAND_PAGE (BYTES_PER_DATA_REGION_OF_SLICE / sizeof(SEALED_SEGMENT_INDEX_NODE))
#define NUM_OF_SEALED_SEGMENT_DATA_NODE_PER_NAND_PAGE (BYTES_PER_DATA_REGION_OF_SLICE / sizeof(SEALED_SEGMENT_DATA_NODE))
typedef struct _SEALED_SEGMENT_INDEX_NODE {
  unsigned int key;
} SEALED_SEGMENT_INDEX_NODE;

typedef struct _SEALED_SEGMENT_DATA_NODE {
  unsigned int lba;
  unsigned int length;
} SEALED_SEGMENT_DATA_NODE;

#endif  // VECTOR1_COSMOS_APP_SRC_SS_SEALEDSEGMENT_H_"
